[build]
  command = "npm install @tailwindcss/postcss@4.1.6 tailwindcss@4.1.6 && npm run build:netlify"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  
# Cache dependencies for faster builds
[build.cache]
  lifecycle = "persist"
  dir = [
    "node_modules",
    "node_modules/.cache"
  ]
  
# Set cache headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Use Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Add compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true