[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"
  NEXT_SHARP_PATH = "/tmp/node_modules/sharp"
  
# Set cache headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle image optimization
[[redirects]]
  from = "/_next/image"
  to = "/.netlify/images"
  status = 200
  force = true
  [redirects.query]
    url = ":url"
    w = ":width"
    q = ":quality"

# Handle fallback to index to support Next.js routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Use Netlify Next.js plugin
[[plugins]]
  package = "@netlify/plugin-nextjs"
  [plugins.inputs]
    includeFiles = []

# Add compression
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true